### PR TITLE
Fixing default arch for tests to match nodejs (x64) and accounting for NODE_ENGINE_CHAKRA

### PR DESCRIPTION
**Pull request by sanjaiganesh**
In previous PR #13 , the default Arch was changed to x64 and missed to change for tests too (when --dest-cpu is not specified).

### CODE REVIEW

**Comment by obastemur** [comment]
@sanjaiganesh did you run the tests after this change?

**Comment by sanjaiganesh** [comment]
As in the mail thread, i couldn't get these tests work with Node UWP. The tests just fail (build ok) without much info.

**Comment by obastemur** [comment]
I see. I meant (i.e. on Desktop, where this framework already passes all the tests)

**Comment by munyirik** [comment]
FYI. The tests will pass now since the --test flag is only building. If you try to run them when windows-uwp has also being used it won't work. Also it will be good to get it building in a UWP project to catch the possibility of a desktop-only API being introduced (this should cause the build to break).

**Comment by sanjaiganesh** [comment]
runtests.js do not take platform and tests just consume the node.dll that is built for windows-uwp platform and pass now. Yes. we need to add a test UWP project as well.

**Comment by munyirik** [comment]
Ok I'll send a PR out later today to at least test building in a UWP app.

**Comment by munyirik** [comment]
otherwise this looks :+1:

**Comment by munyirik** [comment]
Disregard my comment about the tests not being run. After taking a deeper look I can see that it's done here -> https://github.com/openT2T/node-apphost/blob/master/tests/runtests.js#L91

**Comment by sanjaiganesh** [comment]
@arjun-msft Please merge if no other concerns.

**Pull request merged**
